version: "3"

services:
  skynet_freeioe:
    image: kooiot/freeioe:latest
    restart: on-failure
    ports:
      - "8808:8808"
      - "8818:8818"
      - "6606:6606"
    environment:
      - IOE_SN=E1CFC2B8EC
    volumes:
      - freeioe-vol:/usr/ioe:rw

volumes:
  freeioe-vol:
