# This is a basic workflow to help you get started with Actions

name: Get toolchain.tar and Create Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Get the toolchain tar file
        run: wget -nv -O toolchains.tar http://openwrt.kooiot.com/download/toolchains/latest.tar

      - name: Calc MD5 SUM
        id: md5sum_toolchains
        run: echo '::set-output name=MD5SUM::$(md5sum toolchains.tar)'

      - name: Echo MD5 SUM
        run: echo 'The MD5SUM of toolchains.tarr is' ${{ steps.md5sum_toolchains.outputs.MD5SUM }}

      - name: Echo MD5 SUM to file
        run: md5sum toolchains.tar > toolchains.tar.md5

      - name: Delete tag and release
        # You may pin to the exact commit or the version.
        # uses: dev-drprasad/delete-tag-and-release@6bf166de162e06a25bd2055f3be7b2f33f8b5cc8
        uses: dev-drprasad/delete-tag-and-release@v0.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # tag name
          tag_name: toolchain_latest
          # whether to delete release or not
          delete_release: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: toolchain_latest
          release_name: Toolchains
          body: Toolchain Binary Latest
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./toolchains.tar
          asset_name: toolchains.tar
          asset_content_type: application/x-tar

      - name: Upload Release Asset MD5
        id: upload-release-asset-md5 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./toolchains.tar.md5
          asset_name: toolchains.tar.md5
          asset_content_type: plain/text
